version: '3.3'
services:
  discovery:
    image: discovery:latest
    ports:
      - 8761:8761
  api-gateway:
    image: api-gateway:latest
    ports:
      - 8085:8085
    depends_on:
      - discovery