spring:
  application:
    name: api-gateway
  data:
    mongodb:
      host: localhost
      port: 27017
      database: testdb
server:
  port: 8085
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
