spring:
  application:
    name: user-service
  data:
    mongodb:
      //
      host: 192.168.65.2
      port: 27017
      database: filmMaster
server:
  servlet:
    context-path: /user-service
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER:localhost}:8761/eureka/