spring:
  application:
    name: search-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: testdb
security:
  oauth2:
    resource:
      preferTokenInfo: true
      token-info-uri: http://localhost:8080/user-service/oauth/check_token
    client:
      client-id: my-trusted-client
      client-secret: secret

server:
  servlet:
    context-path: /search-service
