spring:
  application:
    name: discovery-server
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    instance-info-replication-interval-seconds: 15
  server:
    enableSelfPreservation: false